# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjust < Formula
  desc "A lazy TUI for just — browse, search, and run recipes without memorizing commands"
  homepage "https://github.com/nickhartjes/lazyjust"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nickhartjes/lazyjust/releases/download/v0.2.0/lazyjust_0.2.0_darwin_amd64.tar.gz"
      sha256 "1ca24ce9f11e3a9bfbed76864af6d70100affa647127a86bc38872af86a7c9ae"

      define_method(:install) do
        bin.install "lazyjust"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nickhartjes/lazyjust/releases/download/v0.2.0/lazyjust_0.2.0_darwin_arm64.tar.gz"
      sha256 "bc5f943163d473f4085f49b121017c1af15d70cebc59e7f14a6ae96cf5492874"

      define_method(:install) do
        bin.install "lazyjust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nickhartjes/lazyjust/releases/download/v0.2.0/lazyjust_0.2.0_linux_amd64.tar.gz"
      sha256 "1bea1238ac2825d54c0f3e801af6e224604a777d539297012e00d591ffea550b"
      define_method(:install) do
        bin.install "lazyjust"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nickhartjes/lazyjust/releases/download/v0.2.0/lazyjust_0.2.0_linux_arm64.tar.gz"
      sha256 "5091cc65783e0459ec9cb836ae3b4bde9e6999a983d21feb23cbfc1528d556f9"
      define_method(:install) do
        bin.install "lazyjust"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazyjust --version")
  end
end
