# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjust < Formula
  desc "A lazy TUI for just — browse, search, and run recipes without memorizing commands"
  homepage "https://github.com/nickhartjes/lazyjust"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nickhartjes/lazyjust/releases/download/v0.5.0/lazyjust_0.5.0_darwin_amd64.tar.gz"
      sha256 "7a19876961fa3d07bb4b3c5a7579af6b852e1d691bb8521eac59f12d8d83442b"

      define_method(:install) do
        bin.install "lazyjust"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nickhartjes/lazyjust/releases/download/v0.5.0/lazyjust_0.5.0_darwin_arm64.tar.gz"
      sha256 "46d634347da8b3b3412675656237882ac58bb553336f7c52b8f249d2cae101d9"

      define_method(:install) do
        bin.install "lazyjust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nickhartjes/lazyjust/releases/download/v0.5.0/lazyjust_0.5.0_linux_amd64.tar.gz"
      sha256 "d56cc95d36d129b3c6aab46e8798150859c06ba0f2b7a5e9e3a902ccf0626528"
      define_method(:install) do
        bin.install "lazyjust"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nickhartjes/lazyjust/releases/download/v0.5.0/lazyjust_0.5.0_linux_arm64.tar.gz"
      sha256 "4e4e84664040a8481c2adde9a8cbc20997e905cc46661f62a7438cdfc9301b7b"
      define_method(:install) do
        bin.install "lazyjust"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazyjust --version")
  end
end
